import { Inter } from "next/font/google";
import "./globals.css";
// import Head from "next/head";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header"; // Importa el Header

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "<pabloMartinez/>",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="./favicon.ico" />
      </Head> */}
      <body
        className={` ${inter.className} pt-16 md:pt-16 lg:px-20 grid grid-cols-1 lg:grid-cols-[auto,1fr] lg:min-h-screen`}>
        <Header /> {/* Agrega el Header */}
        <aside className="bg-gray-800 text-white">
          <Navbar />
        </aside>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
